.gitignore, .swiftlint.yml, FBook.xcodeproj/project.pbxproj, FBook.xcodeproj/project.xcworkspace/contents.xcworkspacedata, FBook.xcworkspace/contents.xcworkspacedata, FBook/AppDelegate.swift, FBook/Assets.xcassets/AppIcon.appiconset/Contents.json, FBook/Base.lproj/LaunchScreen.storyboard, FBook/Base.lproj/Main.storyboard, FBook/Info.plist, FBook/ViewController.swift, FBookTests/FBookTests.swift, FBookTests/Info.plist, FBookUITests/FBookUITests.swift, FBookUITests/Info.plist, Podfile
https://dev.framgia.com/redmine/issues/135774
- Mới tạo project mới, chưa thêm base 😄 
- Các config của Firebase + Fabric khi có sẽ thêm vào sau
=> [Task #135774] [Create base project] Create Project

FBook.xcodeproj/project.pbxproj, FBook/Helpers/Constants.swift, FBook/Models/Book.swift, FBook/Models/Category.swift, FBook/Models/Media.swift, FBook/Models/Review.swift, FBook/Models/SectionBook.swift, FBook/Services/API/API.swift, FBook/Services/API/BookProvider.swift, FBook/Services/API/HomeProvider.swift, FBook/Services/API/UsersProvider.swift
https://dev.framgia.com/redmine/issues/135976
- Thêm các model, api phục vụ cho màn hình trang chủ.
- sửa lỗi chính tả: getOtherUserPprofile
=> [Task#135976] Add model, api for Home screen

FBook.xcodeproj/project.pbxproj, FBook/Helpers/AlertHelper.swift, FBook/Scenes/ForgotPassword/ForgotPasswordConfigurator.swift, FBook/Scenes/ForgotPassword/ForgotPasswordPresenter.swift, FBook/Scenes/ForgotPassword/ForgotPasswordViewController.swift, FBook/Scenes/ForgotPassword/ForgotPasswordViewRouter.swift, FBook/Scenes/Login/LoginConfigurator.swift, FBook/Scenes/Login/LoginPresenter.swift, FBook/Scenes/Login/LoginViewController.swift, FBook/Scenes/Login/LoginViewRouter.swift
https://dev.framgia.com/redmine/issues/135975
- Code lại theo design pattern
- Thêm follow cho màn hình forgot password (chưa có UI, design)
=> [Task #135975] [Login flow] Login screen add MVP Clean Architecture

FBook/Scenes/Book/BookCellConfigurator.swift, FBook/Scenes/Book/BookCellPresenter.swift, FBook/Scenes/Book/BookCollectionViewCell.swift, FBook/Scenes/Book/BookCollectionViewCell.xib
add source of BookCollectionViewCell
=> [Task #136582] [Main screen] Home screen: source of BookCollectionViewCell

FBook/Scenes/Home/Cells/HomeCellConfigurator.swift, FBook/Scenes/Home/Cells/HomeCellPresenter.swift, FBook/Scenes/Home/Cells/HomeHeader.xib, FBook/Scenes/Home/Cells/HomeHeaderConfigurator.swift, FBook/Scenes/Home/Cells/HomeHeaderPresenter.swift, FBook/Scenes/Home/Cells/HomeHeaderView.swift, FBook/Scenes/Home/Cells/HomeTableViewCell.swift, FBook/Scenes/Home/Cells/HomeTableViewCell.xib
https://dev.framgia.com/redmine/issues/136582
=> [Task #136582] [Main screen] Home screen: add source of header and cell of tableview in Home

FBook.xcodeproj/project.pbxproj, FBook/Scenes/Home/Home.storyboard, FBook/Scenes/Home/HomeConfigurator.swift, FBook/Scenes/Home/HomePresenter.swift, FBook/Scenes/Home/HomeViewController.swift, FBook/Scenes/Home/HomeViewRouter.swift
https://dev.framgia.com/redmine/issues/136582
=> [Task #136582] [Main screen] Home screen sources code

FBook/Scenes/Home/HomePresenter.swift, FBook/Scenes/Login/LoginPresenter.swift
=> [Bug # 136582] [Home] Add weak self

FBook.xcodeproj/project.pbxproj, FBook/Helpers/Constants.swift, FBook/Models/ListItems.swift, FBook/Models/Office.swift, FBook/Models/User.swift, FBook/Scenes/Search/SearchPresenter.swift, FBook/Services/API/API.swift, FBook/Services/API/ApiProvider.swift, FBook/Services/API/BaseProvider.swift, FBook/Services/API/BookProvider.swift, FBook/Services/RequestModels/SearchBookParams.swift
https://dev.framgia.com/redmine/issues/136811
=> [Task #136811][Search book] Construct API

FBook/Scenes/Search/Search.storyboard, FBook/Scenes/Search/SearchPresenter.swift, FBook/Scenes/Search/SearchViewController.swift, FBook/Scenes/Search/SearchViewRouter.swift
https://dev.framgia.com/redmine/issues/137098
=> [Task #137098][Search book] Integrate API

FBook/Scenes/Book/BookCollectionViewCell.swift, FBook/Scenes/Home/Cells/HomeCellPresenter.swift, FBook/Scenes/Home/HomePresenter.swift, FBook/Scenes/MenuSetting/MenuSettingPresenter.swift, FBook/Scenes/MenuSetting/MenuSettingViewController.swift, FBook/Scenes/MenuSetting/MenuSettingViewController.xib, FBook/Services/API/API.swift, FBook/Services/API/BookProvider.swift
https://dev.framgia.com/redmine/issues/137057
- Add API see all book in section 
- update design for book cell
- update design for menu setting
=> [Task #137057][Main screen] Add API see all book in section + update design

FBook.xcodeproj/project.pbxproj, FBook/Models/Book.swift, FBook/Scenes/BookDetail/BookDetailPresenter.swift, FBook/Scenes/BookDetail/Cells/BasicDetailTableViewCell.swift, FBook/Scenes/Search/Search.storyboard, FBook/Scenes/Search/SearchBookCell.swift, FBook/Services/API/API.swift, FBook/Services/API/BaseProvider.swift, FBook/Services/API/BookProvider.swift, FBook/Services/RequestModels/BookingBookParams.swift, FBook/Services/RequestModels/SearchBookParams.swift
https://dev.framgia.com/redmine/issues/137361
=> [Task #137361][Borrow book] Construct API

FBook.xcodeproj/project.pbxproj, FBook/Helpers/Constants.swift, FBook/Models/Book.swift, FBook/Scenes/BookDetail/BookDetailPresenter.swift, FBook/Scenes/BookDetail/BookDetailViewController.swift, FBook/Scenes/BookDetail/Cells/BasicDetailTableViewCell.swift, FBook/Scenes/BookDetail/Cells/UserReviewTableViewCell.xib, FBook/Scenes/BookDetail/Cells/UserTableViewCell.swift, FBook/Scenes/BookDetail/Cells/UserTableViewCell.xib, FBook/Scenes/BookDetail/Headers/BookDetailHeaderView.swift, FBook/Scenes/BookDetail/Headers/BookDetailHeaderView.xib
https://dev.framgia.com/redmine/issues/137387
=> [Task #137387][Book Detail] Display reading users and waiting users

FBook.xcodeproj/project.pbxproj, FBook/Scenes/Account/Following/FollowingViewController.swift, FBook/Scenes/BookRequest/BookRequest.storyboard, FBook/Services/API/API.swift, FBook/Services/API/BookProvider.swift, FBook/Services/RequestModels/ApproveBookParams.swift
https://dev.framgia.com/redmine/issues/137375
=> [Task #137375][Approve borrow request] Construct API

FBook.xcodeproj/project.pbxproj, FBook/Helpers/NoResultView/NoDataView.swift, FBook/Helpers/NoResultView/NoDataView.xib, FBook/Scenes/BookRequest/BookRequest.storyboard, FBook/Scenes/BookRequest/Cells/BookWaitingCell.swift, FBook/Scenes/BookRequest/WaitingRequest/WaitingRequestConfigurator.swift, FBook/Scenes/BookRequest/WaitingRequest/WaitingRequestPresenter.swift, FBook/Scenes/BookRequest/WaitingRequest/WaitingRequestViewController.swift, FBook/Scenes/BookRequest/WaitingRequest/WaitingRequestViewRouter.swift, FBook/Scenes/Search/Search.storyboard, FBook/Scenes/Search/SearchPresenter.swift, FBook/Scenes/Search/SearchViewController.swift
https://dev.framgia.com/redmine/issues/137568
=> [Task #137568][Approve borrow request][Waiting Approve Screen] Create UI

FBook.xcodeproj/project.pbxproj, FBook/Models/ListItems.swift, FBook/Scenes/Categories/Category.storyboard, FBook/Scenes/Categories/CategoryConfigurator.swift, FBook/Scenes/Categories/CategoryPresenter.swift, FBook/Scenes/Categories/CategoryRouter.swift, FBook/Scenes/Categories/CategoryViewController.swift, FBook/Services/API/API.swift, FBook/Services/API/CategoryProvider.swift
https://dev.framgia.com/redmine/issues/137571
=> [Task #137571] [Main screen] Categories screen: API + basic class

FBook/Scenes/BookRequest/BookRequest.storyboard, FBook/Scenes/BookRequest/Cells/BookWaitingCell.swift, FBook/Scenes/BookRequest/WaitingRequest/WaitingRequestPresenter.swift, FBook/Scenes/BookRequest/WaitingRequest/WaitingRequestViewController.swift, FBook/Scenes/BookRequest/WaitingRequest/WaitingRequestViewRouter.swift, FBook/Services/API/API.swift, FBook/Services/API/BookProvider.swift
https://dev.framgia.com/redmine/issues/137621
=> [Task #137621][Approve borrow request][Waiting Approve Screen] Integrate API

FBook/Scenes/Categories/Category.storyboard, FBook/Scenes/Categories/CategoryPresenter.swift, FBook/Scenes/Categories/CategoryViewController.swift, FBook/Services/API/API.swift, FBook/Services/API/CategoryProvider.swift
https://dev.framgia.com/redmine/issues/137571
- Ghép API
=> [Task #137571] [Main screen] Categories screen

FBook/Extensions/UIStoryboard+Extensions.swift, FBook/Scenes/Book/BookCollectionViewCell.swift, FBook/Scenes/Book/BookCollectionViewCell.xib, FBook/Scenes/Home/HomePresenter.swift, FBook/Scenes/Home/HomeViewController.swift, FBook/Scenes/Home/HomeViewRouter.swift, FBook/Scenes/Login/Login.storyboard, FBook/Scenes/Login/LoginViewRouter.swift
https://dev.framgia.com/redmine/issues/137815
- Add button login to home screen
- add follow login
- add refresh control home
=> [Login flow] Add button login to home screen, add follow login

FBook/BaseController/BaseViewController.swift, FBook/Scenes/Login/Login.storyboard, FBook/Scenes/Login/LoginViewController.swift
https://dev.framgia.com/redmine/issues/137924
=> [Task #137924][Main screen] fix layout for iOS 11 + X

FBook.xcodeproj/project.pbxproj, FBook/BaseController/BaseNavigationController.swift, FBook/BaseController/BaseTabBarController.swift, FBook/BaseController/BaseViewController.swift, FBook/Scenes/BookRequest/WaitingBooks/WaitingBooksPresenter.swift, FBook/Scenes/Categories/CategoryPresenter.swift, FBook/Scenes/Home/HomePresenter.swift, FBook/Scenes/Home/HomeViewController.swift, FBook/Scenes/SectionBook/SectionBookPresenter.swift, Podfile
https://dev.framgia.com/redmine/issues/138039
=> [Task #138039][Other] Convert to Swift 4.0

FBook/BaseController/BaseViewController.swift, FBook/BaseController/BaseViewPresenter.swift, FBook/BaseController/BaseViewRouter.swift
=> [Task #136897][BaseController] Update back button

FBook.xcodeproj/project.pbxproj, FBook/Extensions/Date+Extensions.swift, FBook/Models/Book.swift, FBook/Models/BookRequest.swift, FBook/Scenes/BookDetail/BookDetailPresenter.swift, FBook/Scenes/BookDetail/Cells/UserTableViewCell.swift, FBook/Scenes/BookRequest/BookRequest.storyboard, FBook/Scenes/BookRequest/BookRequests/BookRequestsPresenter.swift, FBook/Scenes/BookRequest/BookRequests/BookRequestsViewController.swift, FBook/Scenes/BookRequest/Cells/BookRequestCell.swift, FBook/Scenes/BookRequest/Cells/WaitingBookCell.swift, FBook/Services/RequestModels/ApproveBookParams.swift, FBook/Services/RequestModels/BookingBookParams.swift
https://dev.framgia.com/redmine/issues/138256
=> [Task #137981][Book Request Screen] Integrate API

FBook.xcodeproj/project.pbxproj, FBook/BaseController/BaseNavigationController.swift, FBook/BaseController/BaseViewController.swift, FBook/BaseController/BaseViewRouter.swift, FBook/Helpers/Constants.swift, FBook/Helpers/FBSafariViewController.swift, FBook/Scenes/BookDetail/BookDetailViewController.swift, FBook/Scenes/Categories/CategoryRouter.swift, FBook/Scenes/Search/SearchViewController.swift, FBook/Scenes/SectionBook/SectionBookViewController.swift
https://dev.framgia.com/redmine/issues/138424
- Cho thêm chức năng cho 2 action: more tools và feedback
- Chuyển đoạn custom nút back từ baseviewcontroller -> baseNavagationController
=> [Task #138424][Main screen] Add function more tools, feedback

FBook.xcodeproj/project.pbxproj, FBook/BaseController/BaseNavigationController.swift, FBook/BaseController/BaseViewController.swift, FBook/BaseController/BaseViewPresenter.swift, FBook/BaseController/BaseViewRouter.swift, FBook/Models/Review.swift, FBook/Scenes/BookDetail/BookDetail.storyboard, FBook/Scenes/BookDetail/BookDetailPresenter.swift, FBook/Scenes/BookDetail/BookDetailViewController.swift, FBook/Scenes/BookDetail/BookDetailViewRouter.swift, FBook/Scenes/BookDetail/Cells/EmptyTableViewCell.swift, FBook/Scenes/BookDetail/Cells/EmptyTableViewCell.xib, FBook/Scenes/BookDetail/Cells/WriteReviewTableViewCell.swift, FBook/Scenes/BookDetail/Cells/WriteReviewTableViewCell.xib, FBook/Scenes/BookDetail/Headers/BookDetailHeaderView.swift, FBook/Scenes/Home/HomeViewController.swift, FBook/Scenes/Rating/RatingConfigurator.swift, FBook/Scenes/Rating/RatingPresenter.swift, FBook/Scenes/Rating/RatingViewController.swift, FBook/Scenes/Rating/RatingViewRouter.swift, FBook/Services/API/API.swift, FBook/Services/API/BookProvider.swift
https://dev.framgia.com/redmine/issues/138147
=> [Task #138147][Book Detail] Review book

FBook/Helpers/Constants.swift, FBook/Scenes/Search/Search.storyboard, FBook/Scenes/Search/SearchPresenter.swift, FBook/Scenes/Search/SearchViewController.swift, FBook/Scenes/Search/SearchViewRouter.swift
https://dev.framgia.com/redmine/issues/138771
=> [Task #138771][Search book] Enhance UI and connect Detail Book VC

FBook.xcodeproj/project.pbxproj, FBook/Scenes/SortBookPicker/PickerTableViewCell.swift, FBook/Scenes/SortBookPicker/PickerTableViewCell.xib, FBook/Scenes/SortBookPicker/SortBookConfigurator.swift, FBook/Scenes/SortBookPicker/SortBookPresenter.swift, FBook/Scenes/SortBookPicker/SortBookRouter.swift, FBook/Scenes/SortBookPicker/SortBookViewController.swift, FBook/Scenes/SortBookPicker/SortBookViewController.xib, FBook/Services/RequestModels/SearchBookParams.swift
https://dev.framgia.com/redmine/issues/139252
=> [Task #139252][Main screen] Sort book picker

FBook.xcodeproj/project.pbxproj, FBook/Scenes/CategoryPicker/CategoryPickerConfigurator.swift, FBook/Scenes/CategoryPicker/CategoryPickerPresenter.swift, FBook/Scenes/CategoryPicker/CategoryPickerRouter.swift, FBook/Scenes/CategoryPicker/CategoryPickerViewController.swift, FBook/Scenes/CategoryPicker/CategoryPickerViewController.xib
https://dev.framgia.com/redmine/issues/137772
=> [Task #137772][Main screen] Choose category screen

FBook.xcodeproj/project.pbxproj, FBook/Scenes/CategoryPicker/CategoryPickerPresenter.swift, FBook/Scenes/Home/Home.storyboard, FBook/Scenes/Login/Login.storyboard, FBook/Scenes/SectionBook/SectionBookPresenter.swift, FBook/Scenes/SectionBook/SectionBookViewController.swift, FBook/Scenes/SortBookPicker/SortBookPresenter.swift, FBook/Services/API/API.swift, FBook/Services/API/BookProvider.swift, FBook/Services/RequestModels/FilterSortBookParams.swift
- https://dev.framgia.com/redmine/issues/140434
- Integrate API
=> [Task #140434][Main screen] Filter/Sort in section book screen 2

FBook/BaseController/BaseViewController.swift, FBook/BaseController/BaseViewPresenter.swift, FBook/BaseController/BaseViewRouter.swift, FBook/Scenes/BookDetail/BookDetail.storyboard, FBook/Scenes/Home/Cells/HomeCellPresenter.swift, FBook/Scenes/Home/Cells/HomeHeader.xib, FBook/Scenes/Home/Cells/HomeHeaderPresenter.swift, FBook/Scenes/Home/Cells/HomeHeaderView.swift, FBook/Scenes/Home/Cells/HomeTableViewCell.xib, FBook/Scenes/Home/Home.storyboard, FBook/Scenes/Home/HomePresenter.swift, FBook/Scenes/Home/HomeViewController.swift, FBook/Scenes/Home/HomeViewRouter.swift, FBook/Scenes/Workspace/ChooseWorkspacePresenter.swift, FBook/Services/API/API.swift
- Screen name and number: HomeViewController
- Content: Add choose office feature, set cell height and hide seemore button when don't have any book
- Refactor code in baseVC 
- Screenshots: 
-
=> Feature choose office and hide seemore button when don't have book

FBook.xcodeproj/project.pbxproj, FBook/CustomView/.swiftlint.yml, FBook/CustomView/GLViewPagerViewControllerForSwift.swift, FBook/Extensions/UIColor+Extension.swift, FBook/Extensions/UIStoryboard+Extensions.swift, FBook/Extensions/UIViewController+Extention.swift, FBook/Models/Book.swift, FBook/Scenes/Account/AccountPresenter.swift, FBook/Scenes/Account/AccountRouter.swift, FBook/Scenes/Account/Cells/ProfilCell.swift, FBook/Scenes/Account/Personal/PersonalRouter.swift, FBook/Scenes/BookDetail/BookDetail.storyboard, FBook/Scenes/BookDetail/BookDetailPresenter.swift, FBook/Scenes/BookDetail/BookDetailViewRouter.swift, FBook/Scenes/BookDetail/Cells/BasicDetailTableViewCell.swift, FBook/Scenes/BookDetail/Cells/BasicDetailTableViewCell.xib, FBook/Scenes/BookDetail/Cells/OwnerCollectionViewCell.xib, FBook/Scenes/New Group1/BookActivities.storyboard, FBook/Scenes/New Group1/BookActivitiesConfigurator.swift, FBook/Scenes/New Group1/BookActivitiesPresenter.swift, FBook/Scenes/New Group1/BookActivitiesViewController.swift, FBook/Scenes/New Group1/PageViewController.swift, FBook/Scenes/New Group1/UserReadingViewController.swift, FBook/Scenes/New Group1/UserReturnedViewController.swift, FBook/Scenes/New Group1/UserReturningViewController.swift, FBook/Scenes/New Group1/UserReviewViewController.swift, FBook/Scenes/New Group1/UserWaitingViewController.swift, PULL_REQUEST_TEMPLATE.md
- Screen name and number: BookActivitiesVC
- Content: Show book activitivc, 
- Screenshots: 
https://drive.google.com/file/d/1G-7qjFJmz-coew-jtnOZClUn_J5m5wio/view?usp=sharing
-
=> Show book activities screen
